/*
   This file was generated automatically by Alchitry Labs version 1.1.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cga_color_lut_22 (
    input r,
    input g,
    input b,
    input bright,
    output reg [7:0] r_cga_out,
    output reg [7:0] g_cga_out,
    output reg [7:0] b_cga_out
  );
  
  
  
  always @* begin
    
    case ({r, g, b, bright})
      4'h0: begin
        r_cga_out = 8'h00;
        g_cga_out = 8'h00;
        b_cga_out = 8'h00;
      end
      4'h2: begin
        r_cga_out = 8'h00;
        g_cga_out = 8'h00;
        b_cga_out = 8'haa;
      end
      4'h4: begin
        r_cga_out = 8'h00;
        g_cga_out = 8'haa;
        b_cga_out = 8'h00;
      end
      4'h6: begin
        r_cga_out = 8'h00;
        g_cga_out = 8'haa;
        b_cga_out = 8'haa;
      end
      4'h8: begin
        r_cga_out = 8'haa;
        g_cga_out = 8'h00;
        b_cga_out = 8'h00;
      end
      4'ha: begin
        r_cga_out = 8'haa;
        g_cga_out = 8'h00;
        b_cga_out = 8'haa;
      end
      4'h4: begin
        r_cga_out = 8'haa;
        g_cga_out = 8'h55;
        b_cga_out = 8'h00;
      end
      4'he: begin
        r_cga_out = 8'haa;
        g_cga_out = 8'haa;
        b_cga_out = 8'haa;
      end
      4'h1: begin
        r_cga_out = 8'h55;
        g_cga_out = 8'h55;
        b_cga_out = 8'h55;
      end
      4'h3: begin
        r_cga_out = 8'h55;
        g_cga_out = 8'h55;
        b_cga_out = 8'hff;
      end
      4'h5: begin
        r_cga_out = 8'h55;
        g_cga_out = 8'hff;
        b_cga_out = 8'h55;
      end
      4'h7: begin
        r_cga_out = 8'h55;
        g_cga_out = 8'hff;
        b_cga_out = 8'hff;
      end
      4'h9: begin
        r_cga_out = 8'hff;
        g_cga_out = 8'h55;
        b_cga_out = 8'h55;
      end
      4'hd: begin
        r_cga_out = 8'hff;
        g_cga_out = 8'hff;
        b_cga_out = 8'h55;
      end
      4'hf: begin
        r_cga_out = 8'hff;
        g_cga_out = 8'hff;
        b_cga_out = 8'hff;
      end
      default: begin
        r_cga_out = 8'haa;
        g_cga_out = 8'haa;
        b_cga_out = 8'h00;
      end
    endcase
  end
endmodule
