/*
   This file was generated automatically by Alchitry Labs version 1.1.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module hex_add_24 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sum;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum = a + b;
      end
      2'h1: begin
        sum = a - b;
      end
      2'h2: begin
        sum = a * b;
      end
      default: begin
        sum = a + b;
      end
    endcase
    z = (~|sum);
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & (~sum[15+0-:1])) | ((~a[15+0-:1]) & (~(b[15+0-:1] ^ alufn[0+0-:1])) & sum[15+0-:1]);
    n = sum[15+0-:1];
    out = sum;
  end
endmodule
