/*
   This file was generated automatically by Alchitry Labs version 1.1.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     DIGITS = 8
     LEADING_ZEROS = 1
*/
module bin_to_dec_16 (
    input [26:0] value,
    output reg [31:0] digits
  );
  
  localparam DIGITS = 4'h8;
  localparam LEADING_ZEROS = 1'h1;
  
  
  integer i;
  integer j;
  integer scale;
  
  reg [26:0] remainder;
  
  reg [26:0] sub_value;
  
  reg blank;
  
  always @* begin
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      digits[(i)*4+3-:4] = 4'hb;
    end
    remainder = value;
    blank = 1'h0;
    if (value < 27'h5f5e100) begin
      for (j = 5'h07; j >= $signed(1'h0); j = j - 1) begin
        scale = $pow(4'ha, j);
        if (remainder < scale) begin
          if (j != 1'h0 && blank) begin
            digits[(j)*4+3-:4] = 4'ha;
          end else begin
            digits[(j)*4+3-:4] = 1'h0;
          end
        end else begin
          blank = 1'h0;
          sub_value = 1'h0;
          for (i = 4'h9; i >= 1'h1; i = i - 1) begin
            if (remainder < (i + 1'h1) * scale) begin
              digits[(j)*4+3-:4] = i;
              sub_value = i * scale;
            end
          end
          remainder = remainder - sub_value;
        end
      end
    end
  end
endmodule
