/*
   This file was generated automatically by Alchitry Labs version 1.1.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module vga_0816_rom_21 (
    input [7:0] ascii_code,
    input [3:0] row,
    input [2:0] col,
    output reg row_of_pixels
  );
  
  
  
  wire [1-1:0] M_rom_007f_pixel;
  vga_0816_rom_007f_28 rom_007f (
    .ascii_segment(ascii_code[0+6-:7]),
    .row(row),
    .col(col),
    .pixel(M_rom_007f_pixel)
  );
  
  wire [1-1:0] M_rom_80ff_pixel;
  vga_0816_rom_80ff_29 rom_80ff (
    .ascii_segment(ascii_code[0+6-:7]),
    .row(row),
    .col(col),
    .pixel(M_rom_80ff_pixel)
  );
  
  always @* begin
    row_of_pixels = (~ascii_code[7+0-:1]) ? M_rom_007f_pixel : M_rom_80ff_pixel;
  end
endmodule
